### PR TITLE
Add support for visual editor and card selector

### PR DESCRIPTION
**Pull request by dcs8**
Added ability to select the card from the lovelace card picker and to use the visual editor

### CODE REVIEW

**Comment by nervetattoo** [comment]
💯 Wow, thanks! I've been hoping for someone to contribute this, so a million thanks!
I'll test it out and review it properly.

**Comment by nervetattoo** [comment]
Functionality wise it seems sweet.
A few things:

- Name and icon can't be set to false to hide the title. Would it be possible to somehow make that possible? It could be a checkbox to hide it perhaps?
- Most fields should probably be noted as optional. Normally you don't want to set unit, step size etc because the HA defaults will be right.
- Step size should be a numeric field so you can't type in characters. I'm guessing it would break stuff badly.
- A description for what fallback does would be great.
- A link to the readme would also be good to aid people in configuring using the code editor for sensors

**Comment by dcs8** [comment]
All good suggestions, I'll make the changes and update in the next couple days

**Comment by dcs8** [comment]
I've made the changes you suggested. Everything is now labelled as required/optional, I've changed step_size to a slider (with values 0 - 10 and increment of 0.1 - let me know if you want this to be something else). I've made some other changes too, the layout is slightly different and I'm using the home assistant standard entity/icon pickers, which look a little better than the generic input I was using before. I added a link to the github readme although I'm not 100% sure it's in the best location.

To make a toggle for showing/hiding the name and icon, I had to create a new dedicated config option (show_header), instead of using name = false. The problem with 'name' was, even if you set it to false manually, the next time you open the editor it changes it back to the 'false' string, and I couldn't find a way around that. Unfortunately this will be a breaking change for anyone currently using name = false to hide the name.

**Comment by nervetattoo** [comment]
1. The slider for step size looks weird. Just use a regular input or even a drop down with values (you can always just use yaml mode). I guess there are few cases for anything but 0.5 and 1. Then it could even be a distinct choice for `System default` to make it absolutely clear.
2. Hiding the header: Its fine to introduce a new setting for that, but it should still respect `name === false` so it doesn't break existing configs. That will mean some people getting the string false in the editor and then having to change it around, but thats better than breaking existing configs (mine included! 😄)
3. Move the readme link to the paragraph about using the code editor for sensors, thats the point where it gets relevant.

Apart from those it looks solid. Awesome work!

**Comment by dcs8** [comment]
Good point, I wasn't really thinking about how step_size would actually be used. Those other changes have now been made.

**Pull request merged**
