### PR TITLE
Add support for fault icons

### PR DESCRIPTION
**Pull request by kangaroomadman**
Fault icons can be used in the header to display any fault conditions
with the system using binary_sensors.

### CODE REVIEW

**Comment by kangaroomadman** [comment]
This will conflict with the changes for #208 - I'm happy for those to be pulled in first and I can rebase my changes on top.

Depending on width of the toggle label, the positioning of fault icons may need to be reconsidered anyway. Thoughts?

**Comment by clau-bucur** [comment]
Yeah, it does indeed mess up a bit the faults icon posision, but the position is not that bad IMHO.
image

**Comment by nervetattoo** [comment]
I've merged #208 as that was a requested extension to an existing feature. So yeah, this should be rebased on top of that. Regarding placement I would prefer them on the right hand of the title myself, but as I don't see a case for using this myself I'm happy with whatever suits your needs.

Will merge as soon as its updated.

**Comment by kangaroomadman** [comment]
I have rebased the changes, and updated so the fault icons are positioned immediately to the right of the header title.

image

**Pull request merged**
